Accident rates update
ricardocarva/TrendCrash pull request #10
Opened 2024-04-10 00:05 UTC by jesslourenco

- added accident_rate computation and a few modifications on queries 3 and 4
- dates on the where clause for query 2 are beginning and end of lockdowns in US
- no changes on query 1 but please also review it

2024-04-11 22:35 UTC, Matt-Stre requested changes
They all run/look great. The only thing id say is to maybe multiply the accident rate by 10000 so its a more readable number. If we do that don't forget to change the title to something like Accident Rate (Times 10,000)

2024-04-14 18:37 UTC, ricardocarva approved these changes
Lgtm

2024-04-14 18:45 UTC, ricardocarva approved these changes

2024-04-14 18:47 UTC, Matt-Stre approved these changes

2024-04-14 19:01 UTC, merged